spring.application.name=Springdemo
spring.datasource.url=jdbc:postgresql://localhost:5432/Kashish
spring.datasource.username=postgres
spring.datasource.password=radhaji
spring.datasource.driver-class-name=org.postgresql.Driver
